version: "3.7"

services:
  db:
    # В данном случае БД mongo, можно использовать другую
    image: mongo
    ports:
      - 2717:2717

  app:
    # указываем папку в которой лежит dockerfile и собираем образ согласно ему
    build: ./app

    # Указываем как запускать приложение и порт на котором оно будет получать запросы
    command: python ./fastapi_basic.py
    ports:
      - 1235:8080

  # приложение зависит от БД
    depends_on:
      - db